name: nebsquare
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49354
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4f4f4f'
    - '#ff6600'
    - '#000000'
    - '#ffffff'
    - '#cccccc'
  brandStrength: 0.75
  lightness: 0.9375
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
